# Generated by Django 2.2.1 on 2019-05-21 19:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_auto_20190508_1408'),
    ]

    operations = [
        migrations.AlterIndexTogether(
            name='post',
            index_together=set(),
        ),
        migrations.RemoveField(
            model_name='post',
            name='slug',
        ),
    ]
